name: Node CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  prepare:
    runs-on: macos-latest
    name: "Prepare"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: node_modules-

      - name: Install node_modules
        run: |
          npm ci --prefer-offline --no-audit

  android:
    needs: prepare
    runs-on: macos-latest
    env:
      REACT_NATIVE_VERSION: "0.63.4"
    name: "Android"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: node_modules-

      - name: Install node_modules
        run: |
          npm ci --prefer-offline --no-audit

      - name: Lint
        run: |
          npm run lint

      - name: Cache Android build
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.android/build-cache
          key: ${{ runner.os }}-gradle-rn-${{ env.REACT_NATIVE_VERSION }}

      - name: Inject test app path into a job-wide environment variable
        run: |
          DIR=~/rn-android-test-app
          echo "REACT_NATIVE_TEST_APP=$DIR" >> $GITHUB_ENV

      - name: Cache React Native test app
        uses: actions/cache@v2
        with:
          path: ${{ env.REACT_NATIVE_TEST_APP }}
          key: ${{ runner.os }}-rn-android-${{ env.REACT_NATIVE_VERSION }}

      - name: Run Android tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          target: default
          arch: x86_64
          profile: pixel
          avd-name: google-pixel
          script: |
            npm t -- android
        env:
          ANDROID_EMULATOR: google-pixel

  ios:
    needs: prepare
    runs-on: macos-latest
    env:
      REACT_NATIVE_VERSION: "0.62.0"
    name: "iOS"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: node_modules-

      - name: Install node_modules
        run: |
          npm ci --prefer-offline --no-audit

      - name: Lint
        run: |
          npm run lint

      # - name: List environment capabilities
      #   run: |
      #     xcversion --version
      #     xcodebuild -version
      #     xcrun simctl list
      #     xcversion select 12.1

      - name: Create and run iOS simulator
        run: |
          SIMULATOR_RUNTIME=$(echo "iOS 14.4" | sed 's/[ \.]/-/g')
          SIMULATOR_ID=$(xcrun simctl create "iPhone 11" com.apple.CoreSimulator.SimDeviceType.iPhone-11 com.apple.CoreSimulator.SimRuntime.$SIMULATOR_RUNTIME)
          echo "IOS_SIMULATOR=$SIMULATOR_ID" >> $GITHUB_ENV
          xcrun simctl boot $SIMULATOR_ID &

      - name: Cache iOS build
        uses: actions/cache@v2
        with:
          path: ~/Library/Developer/Xcode/DerivedData/Test-*
          key: ${{ runner.os }}-xcodebuild-rn-${{ env.REACT_NATIVE_VERSION }}

      - name: Cache pods and repositories
        uses: actions/cache@v2
        with:
          path: |
            ~/Library/Caches/CocoaPods
            ~/.cocoapods
          key: ${{ runner.os }}-cocoapods-rn-${{ env.REACT_NATIVE_VERSION }}

      - name: Inject test app path into a job-wide environment variable
        run: |
          DIR=~/rn-ios-test-app
          echo "REACT_NATIVE_TEST_APP=$DIR" >> $GITHUB_ENV

      - name: Cache React Native test app
        uses: actions/cache@v2
        with:
          path: ${{ env.REACT_NATIVE_TEST_APP }}
          key: ${{ runner.os }}-rn-ios-${{ env.REACT_NATIVE_VERSION }}

      - name: Run iOS tests
        run: |
          npm t -- ios

      - name: Shutdown iOS simulator
        run: |
          xcrun simctl shutdown $IOS_SIMULATOR
